### ISSUE TITLE
Armor pieces work just by holding them

### ISSUE THREAD

**Issue by EzerArch** [QMXTech/MachineMusePowersuits#14]
Version: 0.11.0.5-QMX

Armor pieces can work just by holding them in hand. For example, you can use the jetpack even if you haven't put the chestplate on, just hold it.

![2015-01-05_20 39 20](https://cloud.githubusercontent.com/assets/6743303/5621327/920c1538-951b-11e4-9e77-72ca259c9f9f.png)

To use uphill and sprint assists just hold the legging. The same goes for the other armor pieces.

**Comment by Korynkai** [comment]
What the? This is odd, I'll definitely have to look into this one. I suspect it's because nothing actually checks (that I've seen at least) whether or not the power armor is actually equipped as armor, as opposed to equipped in-general.

**Comment by EzerArch** [comment]
Let me add a few more details:

* This bug is old, it's prior the 1st QMX release. 
* The mod neither checks if you are equipped with MPS to print messages like "Toggled Flight Control {on|off}".

**Comment by Korynkai** [comment]
I'm sure I can figure out something to take care of this, in fact, I seem to recall a way to get the armor the player is currently wearing. I'll take a look at this as soon as possible.

**Comment by Korynkai** [comment]
Sure enough, there's a method in InventoryPlayer: public ItemStack armorItemInSlot(int) which returns the armor item in the slot specified. Only things from there are module and ticker magic. I am pleased to say this bug will be fixed in the next build.

**Comment by Korynkai** [comment]
Heh, interesting, after thorough re-examination (after finishing our CI environment) I notice MachineMuse implemented her own tick handler instead of overriding onArmorTick it seems. The difference being one is called constantly when the item is in the player's inventory and one is only called when the item is equipped as armor. Though the former could still be used by ensuring that the correct item is in the inventory slot, this is flagged for reimplementation for the next release.

**Comment by Korynkai** [comment]
I am happy to say this is finally fixed internally. Leaving it open until release.

**Comment by EzerArch** [comment]
Excellent!

**Comment by Korynkai** [comment]
Fixed with this release.
