### ISSUE TITLE
Why release v0.11.0.6-QMX doesn't considered stable?

### ISSUE THREAD

**Issue by xJon** [QMXTech/MachineMusePowersuits#25]
I wish to add it to [my modpack](http://www.technicpack.net/modpack/details/the-1710-pack.453902) and as I see it doesn't considered stable so I'm not too sure what should I do. As I understood, in this release all the big bugs got fixed, so there are only minor bugs at the moment. What do you think?

**Comment by Korynkai** [comment]
It's definitely stable enough to add to your modpack! 
However I'm not sure about MachineMuse's own maintenance status and am not sure whether she will seriously continue mod development. As such I am (and have been) stating in my releases to be aware that the "Official" releases come from machinemuse.net, and that there currently are no "Official" releases for 1.7.10 anyway. Though it may be slightly confusing, I'd rather deal with this confusion rather than the following situation:
(MachineMuse creates a release for 1.7.10)->(people download and install)->(people just about attack me for help "xyz feature is broken")->(I have to refer all these people back to MachineMuse, as the problems are in her build)
It's more a disclaimer than anything, i.e. "These mods are _based_ on MachineMuse's mods. However do not go to her for help as they are not maintained by her. Likewise do not come to me for help with her versions."

**Comment by xJon** [comment]
That's understandable, thanks for a quick reply :)
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/197

**Comment by Korynkai** [comment]
You're welcome! Glad to help :smiley:
