### ISSUE TITLE
Is the new version will be released soon?

### ISSUE THREAD

**Issue by xJon** [QMXTech/MachineMusePowersuits#27]
So I'm having [two main bugs](http://bit.ly/17FjhOR) with the mod and I want to know some stuff so I'll think what to do.
As I understood both bugs are in progress, but I wanna know if I should wait for that or no,
Because currently when some people create pants their save just get corrupted with a ticking entity and some of them don't know how to fix that (this is the main bug).
Thanks,
Jon :)

**Comment by Korynkai** [comment]
Yeah, it's just going through testing currently, all bugs but the RiM bug should be finished (and I'm hoping with the latest test version the RiM bug is).

Note: I did label this to read #23, however, this is just due to the fact I would prefer if no more issues appeared here as we've moved to https://bugzilla.qmxtech.com (with fully-integrated anonymous posting).

To see the currenty open bug list for 0.11.0.7-QMX, please look at http://goo.gl/6ex25s. The list of all bugs addressed in 0.11.0.7-QMX is here: http://goo.gl/ZdBwrU

**Comment by xJon** [comment]
I've actually noted that as I understand both bugs have been reported already in [this comment](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/208#issuecomment-75109284), so this issue is not really a bug report (If I'm indeed right).

Anyway I'm very happy to see that progress is being made, thank you for saving this mod!
I can close this one.

**Comment by Korynkai** [comment]
Nope, you're perfectly fine, this is a question that's fine here, but questions are also welcome on bugzilla (the reason for the label -> bugzilla is preferred, our feeds are tied through it). I noted that the links to the bugzilla references were in said comment and had replied to that issue.
